###
GET http://localhost:3000/api/v1/country/all


###
GET http://localhost:3000/api/v1/country/id/65c9f88172b7bc5528a97caf


###
GET http://localhost:3000/api/v1/country/callinCode/+36


###
POST http://localhost:3000/api/v1/country/comment/id/65c9f88172b7bc5528a97cbb
Content-Type: application/json

{
    "comment": "Fanni: human rights violations"
}


###
POST http://localhost:3000/api/v2/country/comment/id/65c9f88172b7bc5528a97cbb
Content-Type: application/json

{
    "comment": "Borat: Borat"
}


###
PATCH http://localhost:3000/api/v2/country/setRuler/id/65c9f88172b7bc5528a97e0f
Content-Type: application/json

{
    "ruler": "Jácint Admiral General"
}


###
DELETE  http://localhost:3000/api/v2/country/id/65c9f88172b7bc5528a97e0f
